name: Tests

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule: [ cron: "42 0 7 * *" ] # https://crontab.guru/#42_0_7_*_*

jobs:
  test:
    runs-on: ubuntu-latest
    strategy: {matrix: {ruby: [ 3.1, 3.2, 3.3, 3.4, '4.0' ]}}
    steps:
      - uses: step-security/harden-runner@6c3c2f2c1c457b00c10c4848d6f5491db3b629df # v2.18.0
        with: { egress-policy: audit }
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: ruby/setup-ruby@7372622e62b60b3cb750dcd2b9e32c247ffec26a # v1.302.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bin/rake
